# Generated by Django 5.2.17 on 2026-09-08 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onchain_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('protocol_onchain_id', models.PositiveBigIntegerField(db_index=True)),
                ('reporter', models.CharField(db_index=True, max_length=42)),
                ('allegation', models.TextField(blank=True)),
                ('evidence_urls', models.JSONField(blank=True, default=list)),
                ('verdict_exploit', models.BooleanField(default=False)),
                ('verdict_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED_HALT', 'Accepted (halt)'), ('REJECTED', 'Rejected'), ('OVERTURNED', 'Overturned'), ('CLEARED', 'Cleared')], db_index=True, max_length=24)),
                ('bond_amount', models.CharField(default='0', max_length=80)),
                ('bond_settled', models.BooleanField(default=False)),
                ('chain_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='protocols.protocol')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
                'ordering': ['-onchain_id'],
            },
        ),
    ]
