# Generated by Django 5.2.17 on 2026-09-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='event_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onchain_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('protocol_onchain_id', models.PositiveBigIntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('REPORT_EVALUATED', 'Report evaluated'), ('CHALLENGE_EVALUATED', 'Challenge evaluated'), ('UNHALT_EVALUATED', 'Unhalt evaluated'), ('APPEAL_FINALIZED', 'Appeal finalized')], db_index=True, max_length=32)),
                ('actor', models.CharField(db_index=True, max_length=42)),
                ('statement', models.TextField(blank=True)),
                ('evidence_urls', models.JSONField(blank=True, default=list)),
                ('consensus_bool', models.BooleanField(default=False)),
                ('consensus_summary', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('bond_amount', models.CharField(default='0', max_length=80)),
                ('bond_disposition', models.CharField(blank=True, max_length=80)),
                ('chain_created_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'verbose_name': 'case event',
                'verbose_name_plural': 'case events',
                'ordering': ['onchain_id'],
            },
        ),
    ]
