# Generated by Django 5.2.17 on 2026-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('protocol_count', models.PositiveIntegerField(default=0)),
                ('case_count', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('contract_address', models.CharField(blank=True, default='', max_length=42)),
            ],
            options={
                'verbose_name': 'sync cursor',
                'verbose_name_plural': 'sync cursor',
            },
        ),
    ]
