# Generated by Django 5.2.17 on 2026-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccursor',
            name='case_event_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
