# Generated by Django 5.2.17 on 2026-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onchain_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HALTED', 'Halted')], db_index=True, max_length=16)),
                ('governor', models.CharField(db_index=True, max_length=42)),
                ('exploit_definition', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('reporter_bond', models.CharField(default='0', max_length=80)),
                ('active_case_id', models.PositiveBigIntegerField(default=0)),
                ('onchain_case_count', models.PositiveIntegerField(default=0)),
                ('chain_created_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'protocol',
                'verbose_name_plural': 'protocols',
                'ordering': ['onchain_id'],
            },
        ),
    ]
