# Generated by Django 5.2.17 on 2026-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='backup_unhalters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='protocol',
            name='halted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
